server:
  port: 8080
spring:
  jpa: #jpa 종류
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #이쁘게 해줌
  mail:
    host: smtp.gmail.com
    port: 587
    username: cafegory@gmail.com
    password: srwd gnjc jvka zfji
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: trace #콘솔에 남기는게 아니라 로그로 남음.
    org.hibernate.type: trace #바인딩된 파라미터까지 볼 수 있음

oauth:
  kakao:
    client-id: dea99a8b573d3e7052b32772749fd70a
    url:
      auth: https://kauth.kakao.com/
      api: https://kapi.kakao.com/
  naver:
    client-id: lCu2oE140nmA93yKzwjb
    client-secret: HJ8nwTnQ7h
    url:
      auth: https://nid.naver.com/
      api: https://openapi.naver.com/


jwt:
  secret: 8MwSDFXBRzEdt7wOObuOMQD3Q622p5jLv4iPXHGCtIbHyf1CdhhtqmTkI46hXmoo69RgwO4RPJ1yMvl60bczOYdZyNbunFiwCci4fyKq8SNYeKN9LSz2CEUhCVKm0Mu0

mail:
  from: cafegory@gmail.com
