spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: cafegory
    password: cafegory!Q@W#E
    url: jdbc:mariadb://localhost:3306/cafegory


  #    url: jdbc:h2:tcp://localhost/~/querydsl
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 500
      #        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace