name: Cafegory-Backend-Dev-CD

env:
  PROFILE: dev
  DOCKER_HUB_REPOSITORY: cafegory2/cafegory_backend_dev

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  backend-docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.ACTION_TOKEN }}

      - name: JDK 11 설정
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Gradlew 권한 설정
        run: chmod +x ./gradlew

      - name: 테스트 실행
        run: ./gradlew test

      - name: Jar 파일 빌드
        run: ./gradlew bootJar
